// Module instructions copy, extracted verbatim from the prototype's
// INSTRUCTIONS object (shown in the pop-up when a tab is clicked).

export interface InstructionsEntry {
  title: string;
  intro: string;
  outputs: string[];
}

export const INSTRUCTIONS: Record<"1" | "2" | "3", InstructionsEntry> = {
  "1": {
    "title": "Activity 1: Subtitle Accuracy Checker",
    "intro": "In this activity, you will test how accurate AI tools are at creating subtitles in English and Traditional Chinese (Cantonese). You will download two short audio clips: one in English and one in Cantonese. You will use three different AI tools (such as Otter.ai or MacWhisper) to generate subtitles for each clip. Next, upload all six transcript files to the website as plain .txt files and type the name of the tool you used for each one. The website will compare your files against the master answer key and show you an accuracy score for each tool. Only the words matter for scoring, paragraph breaks and line breaks are ignored.",
    "outputs": [
      "3 uploaded .txt files for the English video, each labeled with the tool name",
      "3 uploaded .txt files for the Cantonese video, each labeled with the tool name",
      "6 accuracy scores and comparison reports generated by the website",
      "A final summary comparing which tools worked best for each language"
    ]
  },
  "2": {
    "title": "Activity 2: Story Pitch & AI Research",
    "intro": "In this activity, you will practice planning a news story pitch using both your own writing and AI tools. Click the randomizer button on the website to get your assigned news topic and dataset file. Important rule: you must write the headline and 50-word summary entirely by yourself without using AI. You will then use AI tools (such as Perplexity or DeepSeek) to research the topic, find background details, and locate three similar published news stories. You will also upload your dataset to Flourish AI to create a simple chart or graph. Finally, fill in all sections and export your completed pitch.",
    "outputs": [
      "Your full name and English name, and your assigned news topic and downloaded Excel file",
      "An original headline written by you (NO A.I.)",
      "A 50-word story summary written by you (NO A.I.)",
      "Background information about your topic",
      "Ideas for pictures to include in your story",
      "A link or embed code for your Flourish AI chart",
      "A list of 3 similar news stories found by AI, with a brief note explaining why your story is different",
      "A downloaded copy of your finished story pitch"
    ]
  },
  "3": {
    "title": "Activity 3: Data Leak Investigation",
    "intro": "In this group activity, your team of 3 to 4 students acts as investigative journalists working together to solve a case. A company in Kuala Lumpur is secretly trafficking a wild animal, and you have access to a leaked folder containing over 600 emails, invoices, shipping manifests, company registrations, search histories, and photos. Work together on one computer to enter your answers, but search through the documents on your own devices to find the clues. To solve the case, you must identify the trafficked animal, locate the current shipping container, name the guilty executive, and map out where the animal is being sent. For every clue, use the search box to pick the exact file name as proof, you cannot type it in freely. When your team is ready, submit your answers to open the shipping container and complete the rescue mission.",
    "outputs": [
      "Name of the trafficked animal and the exact file name that proves it",
      "Current location (port name, city, shipping container ID) and the image file name used to find it",
      "Name of the guilty executive, an explanation of why they did it, and the document file name that proves it",
      "A timeline of events listing all supporting email, invoice, and audio file names",
      "The final destination port and country",
      "A successful container unlock on the website screen"
    ]
  }
};
